/* Copyright 2025 Punch Software

*/

#ifndef PUNCH_CONFIG_H
#define PUNCH_CONFIG_H

#include <cstdint>

/** As the name implies */
#define ENABLE_DEBUG_TOOLS

#define KEY_ESC 27

#define SCREEN_WIDTH 50
#define SCREEN_HEIGHT 18

#define MAX_ANIMATED_SPRITE_FRAMES 4

#define COLOR_PAIR_NIGHT_BACKGROUND PAIR_YELLOW_DARKBLUE

#define ZOMBIE_BRUTE_SPRITE 'Z'
#define ZOMBIE_SPRITE 'z'
#define SPRINTER_SPRITE 'z'

#define ZOMBIE_DEFAULT_FROZEN 12

#define PEA_SPRITE '.'

#define ROW_LENGTH 48
#define NUM_ROWS 7

/* Entity Config */
#define MAX_ENTITIES_PER_ROW 100

#define MAX_ZOMBIES_PER_ROW 90
#define MAX_PLANTS_PER_ROW 10

#define NORMAL_ZOMBIE_SPEED 1000
#define NORMAL_ZOMBIE_EATING_SPEED 750

#define SPRINTER_ZOMBIE_SPEED 250

/* Peashooter Config */
#define PEASHOOTER_SPRITE 'p'
#define PEASHOOTER_COST 150u

#define REPEATER_SPRITE 'r'
#define REPEATER_COST 250u

#define SNOWPEA_SPRITE 's'
#define SNOWPEA_COST 200u

#define PEASHOOTER_DELAY 3500

#define NUT_SPRITE 'n'
#define NUT_COST 150u

#define CHOMPER_SPRITE_READY 'C'
#define CHOMPER_SPRITE_EATING 'c'
#define CHOMPER_COST 200u
#define CHOMPER_DELAY 30000

#define SUNFLOWER_SPRITE 's'
#define SUNFLOWER_SPRITE_COLLECT 'S'
#define SUNFLOWER_COST 50u
#define SUNFLOWER_DELAY 20000

#define CHERRYBOMB_SPRITE 'c'
#define CHERRYBOMB_COST 150u

#define POTATOMINE_SPRITE 'p'
#define POTATOMINE_COST 50u


#endif /* PUNCH_CONFIG_H */
